In [2]:
import numpy as np
np

<module 'numpy' from 'C:\\Users\\vinay\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [3]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Access Rows

In [4]:
x[0]

array([1, 2, 3])

Single Element

In [5]:
print(x[0,2])

3


Slicing

In [7]:
print(x)
print(x[0:2,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


Statistical Methods

In [10]:
np.sum(x)

45

In [13]:
print(np.min(x))
print(np.max(x))

1
9


In [14]:
np.mean(x)

5.0

Standard Deviation

In [16]:
np.std(x)

2.581988897471611

Matrix Operations

In [18]:
y=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(y)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [19]:
print(np.add(x,y))

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [20]:
print(np.dot(x,y))

[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [22]:
print(np.transpose(y))

[[10 40 70]
 [20 50 80]
 [30 60 90]]


In [25]:
z=np.zeros((3,3),dtype=complex)
z

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])

Iterating through Numpy Arrays

In [26]:
for i in x:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


In [28]:
for i in np.nditer(x):
    print(i)

1
2
3
4
5
6
7
8
9
